website/__init__.py
from flask import Flask
import os


SECRET_KEY = os.urandom(32)
app = Flask(__name__)
app.config["SECRET_KEY"] = SECRET_KEY


from .views import views
app.register_blueprint(views, url_prefix="/")

website/views.py
from datetime import datetime, timedelta, timezone
import json
from flask import Blueprint, render_template, url_for, redirect, request
import os

import markdown

def files_as_dict(directory):
    files = os.listdir(directory)
    files_with_ctime = [(os.path.join(directory, file), os.path.getctime(os.path.join(directory, file))) for file in files]
    files_sorted = sorted(files_with_ctime, key=lambda x: x[1])
    result_dict = {i + 1: file[0] for i, file in enumerate(files_sorted)}
    return result_dict

blogs = files_as_dict("website/blogs/")
json_album_files = files_as_dict('website/albums/')

views = Blueprint("views", __name__)

def get_duration_since_2007():
    start_time = datetime(2007, 9, 5, 1, 0, 0)
    now = datetime.now()

    # Get total duration
    delta = now - start_time

    # Break into components
    total_seconds = int(delta.total_seconds())
    seconds = total_seconds % 60
    minutes = (total_seconds // 60) % 60
    hours = (total_seconds // 3600) % 24
    days_total = delta.days

    years = days_total // 365
    months = (days_total % 365) // 30
    days = (days_total % 365) % 30

    return f"{years:02}:{months:02}:{days:02}:{hours:02}:{minutes:02}:{seconds:02}"

@views.route("/")
def home():
    utc_plus_6 = timezone(timedelta(hours=6))
    current_time = datetime.now(utc_plus_6).strftime("%Y:%m:%d %H:%M:%S%z")

    # Insert colon in timezone offset to match "+06:00"
    formatted_time = current_time[:-2] + ':' + current_time[-2:]
    print(request.remote_addr)
    return render_template("index.html", blogs=blogs, current_date=formatted_time, duration=get_duration_since_2007())

@views.route("/about")
def about():
    return render_template("about.html")

@views.route("/contact")
def contact():
    return render_template("contact.html")

@views.route("/blog")
def blog():
    b_num = request.args.get("b")
    if b_num:
        blog_filepath = blogs[int(b_num)]
        with open(blog_filepath, 'r') as f:
            html_content = markdown.markdown(f.read(), extensions=['fenced_code'])
        return render_template("base_blog.html", blog_content=html_content)
    
@views.route("/alp")
def alp():
    return render_template("albums.html", json_albums=json_album_files)
    

@views.route("/album")
def album():
    album_arg = request.args.get("a")
    if album_arg:
        al_filepath = json_album_files[int(album_arg)]
        with open(al_filepath, 'r') as f:
            json_data = json.load(f)
            print(json_data)
            return render_template("album.html", al=json_data)

website/templates/about.html
{% extends "base.html" %} {% block head %}
{% endblock head %} {% block body %}

Ok, Static Site. No JS

{% endblock body %}

website/templates/album.html
{% extends "min_base.html" %} {% block head %}
{% endblock head %} {% block body %}

<main style="text-align: center;">
  <h2>{{ al.title }}</h2>

  <div class="album">

    <img src="{{ al.cover }}" alt="cover">
    <div class="album-info">

      <span class="info-field">Released: {{ al.released }}</span>
      <span class="info-field">Artist: {{ al.artist }}</span>
      <span class="info-field">Label: {{ al.label }}</span>
      <span class="info-field"> Tracks:
        <ul>  
          {% for track in al.tracks %}
          <li>{{ track }}</li>
          {% endfor %}
        </ul>
      </span>

    </div>

  </div>

</main>

{% endblock body %}

website/templates/albums.html
{% extends "min_base.html" %} {% block head %}
{% endblock head %} {% block body %}

{% for key, value in json_albums.items() %}
        {% set title = value.split('/')[-1] %}
        <li><a href="{{ url_for('views.album', a=key) }}">{{ title }}</a></li>
{% endfor %}

{% endblock body %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <script src="{{ url_for('static', filename='script.js') }}" defer></script>
  <title>Fren Web</title>
  {% block head %}{% endblock %}
</head>

<body>
  <div class="container">
      <div class="navbar">
        <a href="{{url_for('views.home')}}" class="nav-link">[ Home ]</a>
        <a href="{{url_for('views.about')}}" class="nav-link">[ About ]</a>
        <a href="{{url_for('views.contact')}}" class="nav-link">[ Contact ]</a>
        <a href="https://github.com/xonsium" target="_blank" class="nav-link">[ Github ]</a>
      </div>
    <hr style="margin-bottom: 20px;">
    {% block body %}{% endblock %}

    <footer class="cpr">
      <p>&copy; 2025 Faridin Islam. All rights reserved.</p>
    </footer>
</body>

</html>

website/templates/base_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="{{ url_for('static', filename='script.js') }}" defer></script>
    <title>Xons Website</title>
    {% block head %}{% endblock %}
  </head>

  <body>
    <div class="container">
        <header style="text-align: center;">
            <div class="navbar">
                <a href="{{url_for('views.home')}}" class="nav-link">[ Home ]</a>
                <a href="{{url_for('views.about')}}" class="nav-link">[ About ]</a>
                <a href="{{url_for('views.contact')}}" class="nav-link">[ Contact ]</a>
                <a href="https://github.com/xonsium" target="_blank" class="nav-link">[ Github ]</a>
            </div>
        </header>
        <hr style="margin-bottom: 20px;">
        {% block body %}
        {{ blog_content|safe }}
        {% endblock %}
        <footer>
          <p>Author: Faridin Islam</p>
          <p>Email: <a href="mailto:xonsium@tfwno.gf">xonsium@tfwno.gf</a></p>
        </footer>
  </body>
  
</html>

website/templates/contact.html
{% extends "base.html" %} {% block head %}
{% endblock head %} {% block body %}
        <section class="section">
            <div class="social">
                <span>⦿ Facebook</span>
                <span class="separator"></span>
                <a class="nav-link" target="_blank" href="https://www.facebook.com/based.glasses">[ based.glasses ]</a>
            </div>
            <div class="social">
                <span>⦿ Instagram</span>
                <span class="separator"></span>
                <a class="nav-link" target="_blank" href="https://www.instagram.com/faridin.iz">[ faridin.iz ]</a>
            </div>
            <div class="social">
                <span>⦿ Telegram</span>
                <span class="separator"></span>
                <a class="nav-link" target="_blank" href="https://t.me/faridinqn">[ faridinqn ]</a>
            </div>
            <div class="social">
                <span>⦿ Email</span>
                <span class="separator"></span>
                <a class="nav-link" target="_blank" href="mailto:faridin05saif@gmail.com">[ faridin05saif@gmail.com ]</a>
            </div>
        </section>
{% endblock body %}

website/templates/index.html
{% extends "base.html" %} {% block head %}
{% endblock head %} {% block body %}

<section class="info-section">
    <div>
        <img id="profile" src="https://upload.wikimedia.org/wikipedia/en/7/76/Avenged_Sevenfold_cover_2007.jpg" alt="">
    </div>
    <section class="info">
        <div class="social">
            <span>Name</span>
            <span class="separator"></span>
            <span>Faridin Islam</span>
        </div>
        <div class="social">
            <span>Age</span>
            <span class="separator"></span>
            <span>17 yrs</span>
        </div>
        <div class="social">
            <span>Hobbies</span>
            <span class="separator"></span>
            <span>
                <a class="info-link" target="_blank" href="https://www.instagram.com/faridin.iz">Guitar</a>,
                <a class="info-link" target="_blank" href="https://github.com/xonsium">Coding</a>
            </span>
        </div>
        <div class="social">
            <span>Views</span>
            <span class="separator"></span>
            <span>My Own</span>
        </div>
    </section>
</section>



<h3>Small websites/projects</h3>
<ul>
    <li><a target="_blank" href="https://xonsium.github.io/waifu-nft/">Waifu NFT</a></li>
    <li><a target="_blank" href="https://periodic-table-gilt.vercel.app/">Chem? Periodic Table</a></li>
    <li><a target="_blank" href="https://github.com/xonsium/NDC-notice-bot">NDC Notice Bot</a></li>
    <li><a target="_blank" href="https://github.com/xonsium/greyboard">Greyboard</a></li>
    <li><a target="_blank" href="https://github.com/xonsium/NoAuth">NoAuth Spotify Api</a></li>
</ul>

<h3>Blog entries</h3>
<ul>
    {% for key, value in blogs.items() %}
    {% set title = value.split('/')[-1] %}
    <li><a href="{{ url_for('views.blog', b=key) }}">{{ title }}</a></li>
    {% endfor %}
</ul>

<h3>Miscellaneous</h3>
<ul>
    <li><a href="{{ url_for('views.alp') }}">Album Picks</a></li>
</ul>


{% endblock body %}

website/templates/min_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="{{ url_for('static', filename='script.js') }}" defer></script>
    <title>Xons Website</title>
    {% block head %}{% endblock %}
  </head>

  <body>
    <div class="container">
        <header style="text-align: center;">
            <div class="navbar">
                <a href="{{url_for('views.home')}}" class="nav-link">[ Home ]</a>
                <a href="{{url_for('views.about')}}" class="nav-link">[ About ]</a>
                <a href="{{url_for('views.contact')}}" class="nav-link">[ Contact ]</a>
                <a href="https://github.com/xonsium" target="_blank" class="nav-link">[ Github ]</a>
            </div>
        </header>
        <hr style="margin-bottom: 20px;">
        {% block body %}
        {{ blog_content|safe }}
        {% endblock %}
  </body>
  
</html>